name: "tuf-conformance"
description: "TUF client conformance test suite"

inputs:
  entrypoint:
    description: "client-under-test CLI to invoke"
    required: true
  expected-failures:
    description: "Optional list test names expected to fail"
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install test
      run: |
        echo "::group::Install test suite and dependencies"
        sudo apt install faketime
        pip install -e "${{ github.action_path }}"
        echo "::endgroup::"
      shell: bash

    - name: Run test suite
      id: sigstore-conformance
      env:
        ENTRYPOINT: ${{ inputs.entrypoint }}
        EXPECTED_FAILURES: ${{ inputs.expected-failures }}
        TEST_LOCATION: ${{ github.action_path }}/tuf_conformance
      run: |
        pytest -v "$TEST_LOCATION" \
          --entrypoint "$ENTRYPOINT" \
          --expected-failures "$EXPECTED_FAILURES"
      shell: bash
