[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tuf-conformance"
dependencies = [
    "securesystemslib[crypto, pynacl]",
    "tuf",
]
dynamic = ["version"]

[project.scripts]
tuf-conformance = "tuf_conformance.run_tests:main"

[tool.hatch.version]
path = "tuf_conformance/__init__.py"
