[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tuf-conformance"
dependencies = [
    "securesystemslib[crypto, pynacl]==1.1.0" ,
    "tuf==5.0.0",
    "pytest==8.3.1"
]
dynamic = ["version"]

[tool.hatch.version]
path = "tuf_conformance/__init__.py"
